# Generated by Django 3.2.8 on 2022-08-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220404_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping', to='products.orderitem'),
        ),
    ]
